app:
  name: AgentZero
  version: 0.1.0

server:
  host: 0.0.0.0
  port: 8000

llm:
  provider: openai
  model: gpt-3.5-turbo
  api_key: ${OPENAI_API_KEY}
  temperature: 0.7

agent:
  default_max_history: 20
  default_role: assistant 