app:
  name: AgentZero
  version: 0.1.0

server:
  host: 0.0.0.0
  port: 8000

llm:
  provider: openai
  model: gpt-3.5-turbo
  api_key: ${OPENAI_API_KEY}

memory:
  type: vector
  connection: postgresql://user:pass@localhost:5432/db 
  name: AgentZero
  version: 0.1.0

server:
  host: 0.0.0.0
  port: 8000

llm:
  provider: openai
  model: gpt-3.5-turbo
  api_key: ${OPENAI_API_KEY}

memory:
  type: vector
  connection: postgresql://user:pass@localhost:5432/db